version: '2'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database/mongo:/data/db
      - ./database/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  # fastapi:
  #   build:
  #     context: ./
  #     dockerfile: fastapi.dockerfile
  #   volumes:
  #     - './fastapi:/app'
  #   ports:
  #     - 8000:8000
  #   environment:
  #     MONGODB_HOST: mongo
  #     MONGODB_PORT: 27017
  #     MONGODB_USER: ${MONGO_USER}
  #     MONGODB_PASSWORD: ${MONGO_PASSWORD}
  #     PYTHONPATH: /app
  # react:
  #   build:
  #     context: ./
  #     dockerfile: react.dockerfile
  #   volumes:
  #     - './farm-react:/app'
  #   ports:
  #     - 3000:3000